# Generated by Django 3.1.12 on 2021-07-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='users/%Y/%m/%d')),
                ('position', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Изображения продуктов',
                'verbose_name_plural': 'Изображения продуктов',
            },
        ),
    ]
